version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontendapp_c
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: backendapp_c
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./app/node_modules